export { default as Jumbotron } from "./jumbotron/index";
export { default as Footer } from "./footer/index";
export { default as Accordion } from "./accordion/index";
export { default as Header } from "./Header/index";
export { default as OptForm } from "./opt-form/index";
export { default as Feature } from "./features/index";
export { default as Form } from "./form/index";
export { default as Profiles } from "./profiles/index";
export { default as Loading } from "./loading/index";
